### ISSUE TITLE
Real Estates page 

### ISSUE THREAD

**Issue by kiou2** [Hugolify/hugolify-decap-cms#16]
dans **/admin/#/collections/indexes**
les menus correspondants n'apparaissent pas
![image](https://github.com/user-attachments/assets/359c3221-3a9b-4e76-af49-324009b6e2fd)

De même que la page d'accueil :-(

Ma config : 
```
**module.yaml**
  # Core theme
  - path: github.com/hugolify/hugolify-theme-realestates-persons
  - path: github.com/hugolify/hugolify-theme-realestates
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/Hugolify/hugolify-decap-cms
```

Merci !

**Comment by sebousan** [comment]
Bonjour @kiou2,

malheureusement la partie admin a une config à part :
https://www.hugolify.io/docs/cms/decap-cms/#collections

Il faut créer un fichier `/static/admin/app/settings/available-blocks.js`

```js
import realestates from '../content/realestates.js';
import persons from '../content/persons.js';

export default [
  realestates,
  persons
];
```


Je travaille sur une synchro entre les modules chargés et la config admin mais ce n'est pas encore pour maintenant.


Pour la page d’accueil, c'est un manque côté dossier `content`.
Il faut ajouter un fichier `_index.md` avec dedans :
```
---
isIndex: true
title: Accueil
draft: false
---
```
Je vais l’ajouter par défaut à la prochaine version.

Merci pour ce retour.

**Comment by sebousan** [comment]
@kiou2 j’ai mis à jour ce template https://github.com/Hugolify/realestatify-template/
qui est spécifiquement conçu pour les agences immo. Par contre, il est set avec Netlify CMS.

**Comment by kiou2** [comment]
Merci beaucoup Sébastien, ca fonctionne ! 
Et merci à démocratiser ce fantastique CMS qu'est Hugo. 
A bientôt
DM

**Comment by sebousan** [comment]
Avec plaisir, hâte de voir le résultat.

**Comment by sebousan** [comment]
Hello @kiou2,

[realestatify-template](https://github.com/Hugolify/realestatify-template/) est maintenant connecté à [hugolify-admin](https://github.com/Hugolify/hugolify-admin/) ce qui permet de s'affranchir de config pour set les collections.

Au plaisir d’échanger là dessus.

Qu'en est-il du site que tu as réalisé avec `hugolify-theme-realestates` ?
Je suis toujours heureux d'un retour d'expérience.

Merci,
Sébastien
